language: python

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      python: '2.7'
      script: tox -e py27
    - stage: test
      python: '3.6'
      script: tox -e py36
    - stage: test
      python: '3.6'
      script: tox -e pre-commit
    - stage: deploy
      script: skip

env:
  global:
    - BOTO_CONFIG=/dev/null

install: sudo pip install tox-travis

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: yelplabs
  skip_existing: true
  password:
    secure: sJ9Z08e48F2n/+48U45m3+BkrUoGQHiTzXE6dB7kChXaF1eFN6QH9rZYV1EUdTg8bMdExN7Ent841BlE8bOYp6Z3eHkVZZo+nufRzBUOKjeqSQ4/pLIIF2rxiChB0pW+3cYz0mJ6+lORQzmH+n/IbSpiuwWf78J+uLV1FZBoziqscmil0YaNlJp83ZGcM+x5zSy7wa1DyJpHQb4x3bny62it3u+ibEr6xdvwKJEBkcLjSXzJD/pMVtSEzs3F2voh5nkEHUj7PjLjX3ZvPgTMsKTreUmq0iAOR7KU9QKNqpjK2wdLCUHpnLqt0sU9FBciTv8fDtRuwlYtwRBqAp2O5v3yA3/9gWL8hzjtPZfy7i7rsCaxBJNLiSmTCyC+8LnbOHt+Oof36Z/++kMALVMYU8xDu21cUncDxEOYwD67PENFpSwvW9F9H5qliJUAQ5i8xZAyuOwbq7U3Yn3JJjlCZwS1gmUSASEGNKX+FS9mqUa0+5TAkVvkxi3I2T2PwgwxKL08l2x0iloMxJunpflSnkcdVkdJ7wYgo4bQbRG/WM59fmgCr0strDRh/NU18EnKuyIBvK0J1/U9tiYVMUIvwAor+qFDW5B+cvlVqut3yJIhQ599kgcOKyZwc5SoTsLr7NOHL7bsaPLwoNPdhlzJ2SIA8JVhoUNO8D2nYekA7FM=
  on:
    tags: true
    repo: Yelp/amira
    branch: master
    condition: $TRAVIS_BUILD_STAGE_NAME = Deploy
